# Generated by Django 5.1.6 on 2025-08-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_image_alter_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='posts_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
